from .krea2_projector_delta import (
    NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_1,
    NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_1,
)

from .krea2_projector_delta_12 import (
    NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_2,
    NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_2,
)

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(NODE_CLASS_MAPPINGS_1)
NODE_CLASS_MAPPINGS.update(NODE_CLASS_MAPPINGS_2)

NODE_DISPLAY_NAME_MAPPINGS.update(NODE_DISPLAY_NAME_MAPPINGS_1)
NODE_DISPLAY_NAME_MAPPINGS.update(NODE_DISPLAY_NAME_MAPPINGS_2)

WEB_DIRECTORY = "./js"

print("### krea2_projector_delta Loaded")

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]